apiVersion: v1
kind: Namespace
metadata:
  name: python
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-deployment
  namespace: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      namespace: python
      labels:
        app: my-python-app
    spec:
      containers:
      - name: pythondockerrepo
        image: akspython.azurecr.io/test:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-svc
  namespace: python
spec:
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
  type: LoadBalancer
