name: Start AKS
on:
  push:
    branches:
      - master
  schedule:
    - cron: '1 10 * * *'
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkouts repository
        uses: actions/checkout@v2
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_NEW }}
      - name: Start AKS
        run: |
          az aks start --resource-group github-aks-acr --name github-aks-acr-new
