name: Build and Deploy to AKS

on:
  push:
    branches:
      - master
  schedule:
    - cron: '35 0 * * *'
    - cron: '38 0 * * *'      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkouts repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        env:
          ACR_NAME: 'githubactionaksacr.azurecr.io'
        run: |
          docker build -t githubactionaksacr.azurecr.io/python-new:v1 .
          docker login $ACR_NAME -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
          docker push githubactionaksacr.azurecr.io/python-new:v1
      - name: Start AKS
        run: |
          az aks start --resource-group github-aks --name mg-kube-prac
        if: github.event_name == 'schedule' && startsWith(github.event.schedule, '35 0')    
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: github-aks
          cluster-name: mg-kube-prac
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      # - name: create k8s namespace
      #   run: |
      #     kubectl create namespace python
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'python'
          manifests: |
             azure-aks.yaml
          images: githubactionaksacr.azurecr.io/python-new:v1
          pull-images: false 
      - name: Stop AKS
        run: |
          az aks stop --resource-group github-aks --name mg-kube-prac
        if: github.event_name == 'schedule' && startsWith(github.event.schedule, '38 0')      
